# Generated by Django 5.2.15 on 2026-06-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('department', models.CharField(default='General', max_length=100)),
                ('designation', models.CharField(default='Employee', max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
            ],
        ),
    ]
